# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEAM2UUrXbbCSUc_BUQ3-2-7D8rb_638
"""

import pandas as pd

"""# chech the pandas version.

"""

pd.__version__

"""#create the data frame"""

df = pd.DataFrame([10 , 20 ,30 , 40 , 50 , 60],columns =["col_name"])
df

"""#CHECK THE TYPE"""

print(type(df))

"""#CREATE DICTONARY

"""

DATA = {
    "NANE" : ["NILAVA", "SNEHA" , "SANU" , "ABIR" , "SAYAN" , "POUSHALI"],
    "AGE" : [23 , 23 , 22 , 22 , 25 , 22],
    "SALARY" :[25000 , 30000, 25000 , 30000 , 35000 , 60000]
}
print(DATA)

"""#CONVART DICT TO DATAFRAME

"""

df1 = pd.DataFrame(DATA)
df1

# basic dataframe understanding
df1.head(2)

df1.tail(2)

df1.shape

df1.columns

"""#CHANGE COLUMN NAME"""

df1.rename(columns= {'NANE' : 'Full_NAME', 'AGE' : 'Age_in_Years'})

df1.info()

df1.describe()

df1.to_csv("test.csv", index=False)

df4 = pd.read_csv("test.csv")
df4

"""# COLUMN selection"""

df4["NANE"] # single row selection

from ast import Index
df4[["NANE" , "AGE"]]

"""#ROW selection"""

df4.loc[(df4.NANE == "SNEHA") & (df4.SALARY > 25000)]

df4.loc[df4.NANE == "SANU"]

df4.loc[0:2]

"""#iloc (0 to n-1)"""

df4.iloc[0:2]

"""# FILTER"""

df4['AGE']>22

df4[df4['AGE']>22]

df4[(df4['AGE']>22) & (df4['SALARY']>25000)]

"""#use filter using where"""

df4.where((df4['AGE']>22) & (df4['SALARY']>25000) , other ="not elgible")

"""#row and col operation(update , add , delete)"""

df4['GENDER']=(["MALE" , "FEMALE" , "MALE" , "MALE" ,"MALE", "FEMALE"] )

df4

df4['Bonous'] = (df4.SALARY)*0.20

df4

# ADD NEW ROWS
df4.loc[len(df)]=['BIDYUT' , 65 , 100000,'MALE' ,20000]

df4

# update value using index
df4.loc[0 , 'SALARY'] = 90000

df4

df4.drop('Bonous' , axis=1)

df4.drop(df4[df4['NANE']=='SAYAN'].index , axis=0 , inplace=True)

df4

"""#sort value"""

df4.sort_values('SALARY')

# in desecding order
df4.sort_values('SALARY' , ascending= False)

# WORKING WITH DATE VALUE
df4['doj'] = ['2024-01-01', '2024-01-15' , '2024-03-28', '2024-03-23', '2024-04-27', '2024-05-13']
df4

df4['doj'].dtype

df4.info()

"""# convert doj object to date and time"""

df4['doj'] = pd.to_datetime(df4['doj'])
# df4['doj_year'] = df4['doj'].dt.year
# df4['doj_month'] = df4['doj'].dt.month
# df4['doj_day'] = df4['doj'].dt.day

df4.info()

"""#extract year , month , day , dayname"""

df4['doj'].dt.year

df5 = df4['doj'].dt.month

df4['doj'].dt.day

df4['doj'].dt.day_name()

df4['doj'].dt.month_name()

df4['doj2'] = ['01-01-2024', '01-15-2024' , '03-28-2024', '03-23-2024', '04-27-2024', '05-13-2024']
df4

df4.info()

df4['doj2'] = pd.to_datetime(df4['doj2'] , format='%m-%d-%Y')

df4.info()

"""# add 90 days for doj"""

df4['doj2'] + pd.Timedelta(days = 90)

#handeling missing values
df4.isnull()

# we create a nan value in salary

import numpy as np
df4.loc[df4.NANE == 'ABIR' , 'SALARY'] = np.nan

df4

df4.isnull()

df4.isnull().sum()

df4.fillna(0)

"""#AGGREGATION AND GROUP BY"""

df4['NANE'].value_counts()

df4[df4['month']==1].value_counts()

df4['month'] = df4['doj'].dt.month

df4

df4.groupby('month')['SALARY'].sum()

from numpy._core.fromnumeric import mean
df4.groupby('month').agg({'SALARY' : 'mean' , 'NANE' : 'count'})

"""# CONCATINATE AND MARGE TEXT"""

d1 = pd.DataFrame({'ID' : [1 , 2 , 3] , 'NAME' : ['A' , 'B' , 'C']})
d2 = pd.DataFrame({'ID' : [1, 2 , 2, 4] , 'Score' : [800 , 40 , 60 , 50]})

pd.concat([d1, d2] , axis=0)

pd.concat([d1, d2] , axis=1)

"""#marge(join)"""

pd.merge(d1 , d2 , how='inner' , on='ID')

pd.merge(d1 , d2 , how='inner' , left_on='ID' , right_on='ID')

